language: csharp
solution: Level2Pic.sln
install:
  - cd ./src
  - nuget restore Level2Pic.sln
  - nuget install xunit.runner.console -Version 2.4.0 -OutputDirectory testrunner
script:
  - cd ./src
  - xbuild /p:Configuration=Release Level2Pic.sln
  - mono ./testrunner/xunit.runner.console.2.4.0/tools/net471/xunit.console.exe ./src/Level2Pic.Tests/bin/Release/Level2Pic.Tests.dll